[package]
name = "wait_for"
version = "0.1.5"
edition = "2021"
description = "async waiter for testing"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-executor = "1.13.0"
futures-lite = "2.3.0"
tokio = { version = "1.39.2", features = ["full"] }