[package]
name = "wait_for"
version = "0.1.4"
edition = "2021"
description = "async waiter for testing"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
