[package]
name = "crate_gen"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
[dependencies.codegen_utils]
path ="../codegen_utils"
version = "0.1.4"
registry = "estuary"
