[workspace]
members = [
    "web_framework",
    "build_lib",
    "http_macro",
    "mongo_repo",
    "module_macro_lib",
    "security_model",
    "data_framework",
    "module_macro",
    "delegator_test",
    "hyper",
    "test_app",
    "knockoff_logging",
    "rust_spring_macro",
    "wait_for",
    "module_macro_codegen",
    "module_macro_shared",
]
