[workspace]
members = [
    "web_framework",
    "build_lib",
    "http_macro",
    "mongo_repo",
    "module_macro_lib",
    "security_model",
    "data_framework",
    "module_macro",
    "delegator_test",
    "delegator_macro_rules",
    "hyper",
    "test_app",
    "rust_spring_macro"
]
