[workspace]
members = [
    "web_framework",
    "http_macro",
    "mongo_repo",
    "security_model",
    "data_framework",
    "delegator_macro",
    "delegator_test",
    "delegator_macro_rules"
]
