[all]
[all.all]
proc-macro2 = "1.0"
quote = "1.0"
serde = "1.0.137"
syn = {features = ["full"], version = "1.0"}
[pre_compile.zero]
knockoff_delegator_factories = {path = "../knockoff_delegator_factories"}
