[token_provider.handler_mapping]
provider_path = "handler_mapping::HandlerMappingBuilder"
provider_ident = "HandlerMappingTokenProvider"
path = "../../handler_mapping"

[token_provider.handler_mapping.dependencies]
quote = "1.0"
syn = {version = "1.0", features = ["full"]}
proc-macro2 = "1.0"
serde = "1.0.137"
[token_provider.handler_mapping.dependencies.web_framework]
path = "../../web_framework"
name = "web_framework"
[token_provider.handler_mapping.dependencies.web_framework_shared]
path = "../../web_framework_shared"
name = "web_framework_shared"

[parse_provider.security_parse_provider]
provider_path = "security_parse_provider::SecurityParseProvider"
provider_ident = "SecurityParseProviderBuilder"
path = "../../security_parse_provider"