[package]
name = "test_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.18.2"
lazy_static = "1.4.0"
serde = "1.0.137"
[dependencies.web_framework]
path = "../web_framework"
[dependencies.hyper]
path = "../hyper"
