[package]
name = "token_stream_provider"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0"
syn = {version = "1.0", features = ["full"]}

[dependencies.module_macro_lib]
path = "../module_macro_lib"
[dependencies.module_macro_shared]
path = "../module_macro_shared"