[package]
name = "web_framework"
version = "0.1.5"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.87"
async-std = "1.11.0"
async-trait = "0.1.53"
base64 = "0.13.0"
tokio-test = "*"
futures = "0.3.25"
paste = "1.0.6"
circular = "0.3.0"
derive-syn-parse = "0.1.5"
syn = {version = "1.0", features = ["full"]}
quote = "1.0"
dynpath = "0.1.4"
[dependencies.data_framework]
version = "0.1.5"
registry = "estuary"
path ="../data_framework"
[dependencies.mongo_repo]
version = "0.1.5"
registry = "estuary"
path ='../mongo_repo'
[dependencies.knockoff_security]
version = "0.1.5"
registry = "estuary"
path ="../knockoff_security"
[dependencies.web_framework_shared]
version = "0.1.5"
registry = "estuary"
path ="../web_framework_shared"
[dependencies.codegen_utils]
version = "0.1.5"
registry = "estuary"
path ="../codegen_utils"
[dependencies.authentication_gen]
version = "0.1.5"
registry = "estuary"
path ="../authentication_gen"

[build-dependencies]
syn = {version = "1.0", features = ["full"]}
[build-dependencies.codegen_utils]
version = "0.1.5"
registry = "estuary"
path ="../codegen_utils"
[build-dependencies.build_lib]
version = "0.1.5"
registry = "estuary"
path ="../build_lib"
[build-dependencies.web_framework_shared]
version = "0.1.5"
registry = "estuary"
path ="../web_framework_shared"
